import { Component, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LanguageSwitcherComponent } from '../language-switcher/language-switcher';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, LanguageSwitcherComponent],
  templateUrl: './layout.html',
  styleUrl: './layout.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Layout {
  readonly codeLines = [
    "import { Component, OnInit, signal, computed } from '@angular/core';",
    "import { HttpClient } from '@angular/common/http';",
    "import { Observable, of, map, catchError } from 'rxjs';",
    '',
    '@Injectable({ providedIn: "root" })',
    'export class PortfolioService {',
    '  private readonly apiUrl = "https://api.portfolio.com";',
    '',
    '  constructor(private http: HttpClient) {}',
    '',
    '  getProjects(): Observable<Project[]> {',
    '    return this.http.get<Project[]>(`${this.apiUrl}/projects`)',
    '      .pipe(',
    '        map(projects => projects.filter(p => p.active)),',
    '        catchError(() => of([]))',
    '      );',
    '  }',
    '}',
    '',
    '@Component({',
    "  selector: 'app-hero',",
    '  standalone: true,',
    '  imports: [CommonModule, HttpClientModule],',
    "  templateUrl: './hero.html',",
    "  styleUrl: './hero.scss'",
    '})',
    'export class HeroComponent implements OnInit {',
    '  private readonly portfolioService = inject(PortfolioService);',
    '  private readonly router = inject(Router);',
    '',
    '  public projects = signal<Project[]>([]);',
    '  public isLoading = signal<boolean>(true);',
    '',
    '  public readonly skills = computed(() =>',
    '    this.projects().flatMap(p => p.technologies)',
    '  );',
    '',
    '  ngOnInit(): void {',
    '    this.loadProjects();',
    '  }',
    '',
    '  private loadProjects(): void {',
    '    this.portfolioService.getProjects()',
    '      .pipe(takeUntilDestroyed())',
    '      .subscribe({',
    '        next: (projects) => {',
    '          this.projects.set(projects);',
    '          this.isLoading.set(false);',
    '        },',
    '        error: (err) => console.error(err)',
    '      });',
    '  }',
    '',
    '  navigateToProject(id: string): void {',
    '    this.router.navigate(["/projects", id]);',
    '  }',
    '}',
    '',
    '@Pipe({ name: "highlight" })',
    'export class HighlightPipe implements PipeTransform {',
    '  transform(value: string, term: string): string {',
    '    if (!term) return value;',
    '    return value.replace(',
    '      new RegExp(term, "gi"),',
    '      `<span class="highlight">$&</span>`',
    '    );',
    '  }',
    '}',
    '',
    '@Directive({ selector: "[appHoverEffect]" })',
    'export class HoverEffectDirective {',
    '  @HostListener("mouseenter", ["$event"])',
    '  onMouseEnter(event: MouseEvent): void {',
    '    const element = event.target as HTMLElement;',
    '    element.style.transform = "scale(1.05)";',
    '    element.style.transition = "transform 0.3s ease";',
    '  }',
    '',
    '  @HostListener("mouseleave", ["$event"])',
    '  onMouseLeave(event: MouseEvent): void {',
    '    const element = event.target as HTMLElement;',
    '    element.style.transform = "scale(1)";',
    '  }',
    '}',
    '',
    '@Guard({',
    '  canActivate: [AuthGuard],',
    '  canDeactivate: [UnsavedChangesGuard]',
    '})',
    'export class ProjectGuard implements CanActivate {',
    '  canActivate(route: ActivatedRouteSnapshot): boolean {',
    '    return !!route.params["id"];',
    '  }',
    '}',
    '',
    '@Injectable()',
    'export class HttpInterceptor implements HttpInterceptor {',
    '  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {',
    '    const cloned = req.clone({',
    '      setHeaders: { "Authorization": `Bearer ${this.getToken()}` }',
    '    });',
    '    return next.handle(cloned).pipe(',
    '      catchError((error) => this.handleError(error))',
    '    );',
    '  }',
    '}',
    '',
    'export interface Project {',
    '  id: string;',
    '  name: string;',
    '  description: string;',
    '  technologies: string[];',
    '  active: boolean;',
    '}',
  ];
}
